services:
  - type: web
    name: sudharshan-portfolio-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set in dashboard
